name = "YourPkgHasArrived"
uuid = "768e9b06-6894-49fa-9260-00ec6ad7f7ad"
authors = ["Tristan_Weaver <tsw5383@psu.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Distributions = "0.25.122"
NFFT = "0.14.0"
Test = "1.11.0"
